services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn --worker-class=gevent --workers=4 --bind 0.0.0.0:8000 src.core.wsgi:application"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - db_data:/app/db  # Монтируем volume как каталог
    environment:
      DJANGO_SETTINGS_MODULE: "src.core.settings"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - celery

  celery:
    build: .
    command: >
      sh -c "/app/.venv/bin/celery -A celery_app worker -l info -B" # *** Added '-B' to start Celery Beat ***
    volumes:
      - db_data:/app/db  # Celery тоже использует volume как каталог
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles
    depends_on:
      - web

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  static_volume:
  media_volume:
  db_data: