# Generated by Django 5.1.7 on 2025-03-31 13:46

import django.utils.timezone
from django.db import migrations, models

import src.registrations.models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Регистрация",
                "verbose_name_plural": "Регистрации",
            },
        ),
        migrations.RemoveField(
            model_name="registration",
            name="registration_time",
        ),
        migrations.AddField(
            model_name="registration",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Время создания регистрации",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registration",
            name="expires_at",
            field=models.DateTimeField(
                db_index=True,
                default=src.registrations.models.get_default_expires_at,
                help_text="Время, после которого ожидающая регистрация будет автоматически отклонена, если статус не изменится",
                verbose_name="Истекает в",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Время последнего обновления"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("confirmed", "Подтверждена"),
                    ("rejected", "Отклонена"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="Статус регистрации",
            ),
        ),
    ]
